<?php
$config=[
    'student'=>[
        [
            'field'=>'s_firstName',
            'label'=>'s_firstName',
            'rules'=>'required|alpha_numeric_spaces'
        ],[
            'field'=>'s_lastName',
            'label'=>'s_lastName',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'contact1',
            'label'=>'contact1',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'contact2',
            'label'=>'contact2',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'gender',
            'label'=>'gender',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'classIdFK',
            'label'=>'classIdFK',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'sectionIdFK',
            'label'=>'sectionIdFK',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'address',
            'label'=>'address',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'dob',
            'label'=>'dob',
            'rules'=>'required|alpha_dash'
        ],
        [
            'field'=>'email',
            'label'=>'email',
            'rules'=>'required|valid_email'
        ],
        [
            'field'=>'dob',
            'label'=>'dob',
            'rules'=>'required'
        ]
    ],
    'modifyClass'=>[
        [
            'field'=>'className',
            'label'=>'Class Name',
            'rules'=>'required|alpha_numeric_spaces|is_unique[sdb_tbl_classes.className]'
        ],
        [
            'field'=>'registrationFees',
            'label'=>'Registration Fee',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'yearlyTuitionFees',
            'label'=>'Yearly Tuition Fee',
            'rules'=>'required|numeric'
        ]
    ],
    'modifyFees'=>[
        [
            'field'=>'registrationFees',
            'label'=>'Registration Fee',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'yearlyTuitionFees',
            'label'=>'Yearly Tuition Fee',
            'rules'=>'required|numeric'
        ]
    ],
    'sectionName'=>[
        [
            'field'=>'sectionName',
            'label'=>'Section Name',
            'rules'=>'required|alpha|is_unique[sdb_tbl_sections.sectionName]'
        ]
    ],
    'payment'=>[
        [
            'field'=>'studentID',
            'label'=>'studentID',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'feeScheduleId',
            'label'=>'feeScheduleId',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'paymentTypeId',
            'label'=>'paymentTypeId',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'paymentDate',
            'label'=>'paymentDate',
            'rules'=>'required'
        ],
        [
            'field'=>'paymentAmount',
            'label'=>'paymentAmount',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'notes',
            'label'=>'notes',
            'rules'=>'alpha_numeric_spaces'
        ]
    ],
    /**/
    'modify_institute_rules'=>[
        [
            'field'=>'name',
            'label'=>'Name',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'contact',
            'label'=>'contact',
            'rules'=>'required|numeric'
        ],
        [
            'field'=>'address',
            'label'=>'address',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'establishedIn',
            'label'=>'established In',
            'rules'=>'required|alpha_dash'
        ],
        [
            'field'=>'registrationNo',
            'label'=>'registration No',
            'rules'=>'required|alpha_numeric_spaces'
        ],
        [
            'field'=>'dueDays',
            'label'=>'dueDays',
            'rules'=>'required|numeric|max_length[3]'
        ],
        [
            'field'=>'monthlyFees',
            'label'=>'monthlyFees',
            'rules'=>'required|numeric|max_length[3]'
        ]
    ],
    'profile_email_rule'=>[
        [
            'field'=>'userEmail',
            'label'=>'user Email',
            'rules'=>'required|valid_email|is_unique[sdb_tbl_users.userEmail]'
        ]
    ],
    'profile_userName_rule'=>[
        [
            'field'=>'userName',
            'label'=>'user Name',
            'rules'=>'required|alpha_numeric|is_unique[sdb_tbl_users.userName]'
        ]
    ],
    'profile_fields_rule'=>[
        [
            'field'=>'u_firstName',
            'label'=>'First Name',
            'rules'=>'required|trim|min_length[4]|alpha_numeric_spaces'
        ],
        [
            'field'=>'u_lastName',
            'label'=>'Last Name',
            'rules'=>'required|trim|min_length[4]|alpha_numeric_spaces'
        ],
        [
            'field'=>'secretQuestion',
            'label'=>'Secret Question',
            'rules'=>'required|min_length[3]|alpha_numeric_spaces'
        ],
        [
            'field'=>'secretAnswer',
            'label'=>'Secret Answer',
            'rules'=>'required|min_length[3]|alpha_numeric_spaces'
        ]
    ],
];
